apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: 3b91396cde1f756b4fd30a4cc7d0500ebe92ef33

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml