apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: 3faf2b4caf143777c73b37b686035c1ea36f0bfa

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml