apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: 58dc61a194ca86a6a04206d96880c42f170747f2

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml