spring:
  cloud:
    gateway:
      server:
        webflux:
          global-cors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: ["https://*.jifelog.com", "https://localhost:[*]", "https://local.jifelog.com:[*]"]
server:
  reactive:
    session:
      cookie:
        secure: false

jifelog:
  jwt:
    issuer: dev-gateway.jifelog.com
