spring:
  config:
    import:
      - "classpath:application-secret.yaml"
  application:
    name: jifelog-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-api
              uri: http://auth-api-${spring.profiles.active}.services-${spring.profiles.active}.svc.cluster.local:8080
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
  data:
    redis:
      host: ${secret.redis.host}
      password: ${secret.redis.password}

jifelog:
  jwt:
    secret: ${secret.jwt.secret}
    issuer: jifelog-gateway
    audience: jifelog-internal-services
    header-name: X-Jifelog-JWT
    ttl-seconds: 60
