apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: dev-9e1138d2c95ae5ed7f76fe2960424eef3fc01bc0

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml