apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: dev-81b1bdb30b5df7e90d8a71a6988accf888b1fc5a

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml