apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: dev-9fe4eab60819419baf9fb6e322352f5ae8f7c484

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml