apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-gateway
    newName: jhjun07/jifelog-gateway
    newTag: dev-f7a5c66bf06b9742f0577ee6b1b0f0249d9d5e58

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml