apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  ingressClassName: public
  tls:
    - hosts:
        - dev-gateway.jifelog.com
      secretName: tls-secret-dev
  rules:
    - host: dev-gateway.jifelog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80